### ISSUE TITLE
Error: spawn dot ENOENT

### ISSUE THREAD

**Issue by lieeuwos** [vogloblinsky/gulp-angular-architecture-graph#2]
Hi, this is how my gulpfile.js looks:

```
var ngGraph = require('gulp-angular-architecture-graph');

// Source path
var APP = 'app';

// Bower components path
var LIB = APP + '/lib';

gulp.task('graph', function(){
  gulp.src([APP + '/**/*.js', '!' + LIB + "/**/*"])
    .pipe(ngGraph())
})
```

I am getting this error:

```
D:\MyPath\src>gulp graph
[14:13:37] Using gulpfile D:\MyPath\src\gulpfile.js
[14:13:37] Starting 'graph'...
[14:13:37] Finished 'graph' after 8.81 ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn dot ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

D:\MyPath\src>
```

**Comment by vogloblinsky** [comment]
Hi,

Did you follow windows requirements instructions ?

https://github.com/vogloblinsky/gulp-angular-architecture-graph#windows-7

Regards

**Comment by lieeuwos** [comment]
I first installed the latest version of graphviz 2.38, in the designated folder C:\Program Files (x86)\Graphviz2.38 and then added the C:\Program Files (x86)\GraphvizX.XX\bin to PATH

**Comment by vogloblinsky** [comment]
Just tested in a windows VM.
With a fresh install of Node.JS, gulp in global, the plugin, and graphviz, i get the same error.
You miss to replace the X.XX with 2.38 in your PATH, it should be C:\Program Files (x86)\Graphviz2.38\bin
Adding the correct link in my PATH fixes the error, don't miss to restart your terminal.
Regards

**Comment by icvitkovac** [comment]
@lieeuwos  - and of course, don't forget to close all instances of the terminal (power shell, command prompt, etc.) and to open it again.
